
  CREATE TABLE PRODUCTS
   (	ID NUMBER, 
	NAME VARCHAR2(255 BYTE), 
	DESCRIPTION VARCHAR2(255 BYTE), 
	RELATEDITEMS VARCHAR2(255 BYTE)
   ) ;

CREATE TABLE USER_LOGIN
      (	
   	NAME VARCHAR2(255 BYTE), 
   	PASSWORD VARCHAR2(255 BYTE)
   	
   ) ;